### ISSUE TITLE
Bugs in v collective implementation?

### ISSUE THREAD

**Issue by cjf00000** [jeffhammond/BigMPI#24]
I am using MPIX_Allgatherv_x and got a crash, and found MPI_Allgather is working fine.

When I dig into the source code, I found in MPIX_Allgatherv_x (vcollectives.c:315), it called BigMPI_Collective with recvtypes=NULL.

But in BigMPI_Collective (vcollectives.c:208), I found it is trying to access recvtypes[i], giving me a segfault.

Is it a bug or I am missing anything?

This is my test code which got a segfault

          int send = my_rank;
          int recv[2];
          MPI_Count sendcount = 1;
          MPI_Count recvcounts[] = {1, 1};
          MPI_Aint displs[] = {0, 1};
          MPIX_Allgatherv_x(&send, sendcount, MPI_INT,
                          recv, recvcounts, displs, MPI_INT,
                          MPI_COMM_WORLD);

I hacked the code by myself adding something like

        MPI_Datatype * sendtypes  = malloc(size*sizeof(MPI_Datatype)); assert(sendtypes!=NULL);
        MPI_Datatype * recvtypes  = malloc(size*sizeof(MPI_Datatype)); assert(recvtypes!=NULL);
        for (int i=0; i<size; i++) sendtypes[i] = sendtype;
        for (int i=0; i<size; i++) recvtypes[i] = recvtype;

after that it works fine.

**Comment by jeffhammond** [comment]
Thanks for reporting this!  There was a copy-and-paste fail (mine).  All of the v-collectives should use the scalar type instead of the type vector.  I will push a fix in a moment.  Can you please try again?
