### ISSUE TITLE
Missing bigmpiconf.h?

### ISSUE THREAD

**Issue by faizabidi** [jeffhammond/BigMPI#35]
While making it, I get the below error:
/BigMPI/src/bigmpi_impl.h:4:24: fatal error: bigmpiconf.h: No such file or directory

Is there a file missing somewhere or am I doing it wrong? I am using the master latest branch on CentOS with Mpich 3.2.

Thanks!

**Comment by jeffhammond** [comment]
Can you provide the full set of commands you used to get this error?

The following is working for me:
```
cd BigMPI
./autogen.sh && \
mkdir build ; \
cd build && \
../configure CC=mpicc && \
make -j checkprogs && \
make check
```

**Comment by faizabidi** [comment]
Yeah, I figured that eventually. Initially I was trying  *as is* mentioned in the INSTALL. Suggest putting all this information in the INSTALL file. Thanks!

**Comment by jeffhammond** [comment]
Ah, thanks for letting me know.  @gentryx wrote those docs for the CMake crowd.  I don't use CMake but it seems there may be a regression there.

I've added the corresponding Autotools docs.

**Comment by gentryx** [comment]
How about getting rid of CMake and only leaving Autotools and friends? No need to duplicate functionality. I can file a PR for that.

**Comment by jeffhammond** [comment]
As much as I dislike it, people use CMake.  I don't want people to not use BIgMPI because of build system issues. If you have time to contribute, can you fix what's broken?
